# Standalone HBase
# assingning port names larger than 14 characters cause GKE to silently
# ignore deployment and leave pods to 0/0
---
apiVersion: v1
kind: Service
metadata:
  name: hbase
  labels:
    app: hbase
spec:
  ports:
    - port: 2181
      name: zk-port
    - port: 16000
      name: m-p
    - port: 16010
      name: m-i-p
    - port: 16020
      name: r-p
    - port: 16030
      name: r-i-p
    - port: 8080
      name: rest-p
  clusterIP: None
  selector:
    app: hbase
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: hbase
spec:
  selector:
    matchLabels:
      app: hbase
  serviceName: hbase
  replicas: 1
  template:
    metadata:
      labels:
        app: hbase # Pod template's label selector
    spec:
      containers:
        - name: hbase
          image: cellos/hbase:2.1.1-f810f88
          resources:
            requests:
              memory: "4Gi"
          ports:
            - containerPort: 2181
              name: zk-port
            - containerPort: 16000
              name: m-p
            - containerPort: 16010
              name: m-i-p
            - containerPort: 16020
              name: r-p
            - containerPort: 16030
              name: r-i-p
            - containerPort: 8080
              name: rest-p
          command:
            - sh
            - -c
            - /entrypoint.sh standalone /hbase/bin/start-hbase.sh &&  tail -f  /hbase/bin/../logs/*
          volumeMounts:
            - name: hbase-datadir
              mountPath: /var/lib/hbase
            - name: zk-datadir
              mountPath: /var/lib/zookeeper

  volumeClaimTemplates:
    - metadata:
        name: hbase-datadir
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi
    - metadata:
        name: zk-datadir
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi
